// pcell_finished.fe: Dump of structure.

// datafilename: C:\Users\User\Desktop\Bachelorarbeit\src\surfaceEvolver\pcell.fe
vertices_predicted       120
edges_predicted          153
facets_predicted          33
facetedges_predicted      97
bodies_predicted           2
quantities_predicted            0
method_instances_predicted      0
// Total energy: 0.19592331373791
SOAPFILM

LINEAR

SCALE: 0.292999798311587

PARAMETER band_flag =  0 

VIEW_TRANSFORM_GENERATORS 9 
1  0  0  0  
0  1  0  0  
0  0  -1  2  
0  0  0  1  

0  1  0  0  
1  0  0  0  
0  0  1  0  
0  0  0  1  

1  0  0  0  
0  -1  0  0  
0  0  1  0  
0  0  0  1  

0  0  1  0  
0  1  0  0  
1  0  0  0  
0  0  0  1  

-1  0  0  2  
0  1  0  0  
0  0  1  0  
0  0  0  1  

1  0  0  0  
0  -1  0  2  
0  0  1  0  
0  0  0  1  

-1  0  0  -2  
0  1  0  0  
0  0  1  0  
0  0  0  1  

1  0  0  0  
0  -1  0  -2  
0  0  1  0  
0  0  0  1  

1  0  0  0  
0  1  0  0  
0  0  -1  -2  
0  0  0  1  

TOTAL_TIME 544.193

CONSTRAINT_TOLERANCE: 1e-012

VIEW_MATRIX 
 0.430253576905054  -0.804574800858858   0.409318029633856   0.000000000000000  
 0.475585784485737   0.587435677939110   0.654780486788743   0.000000000000000  
-0.767267893994986  -0.087055810300913   0.635390639478862   0.000000000000000  
 0.000000000000000   0.000000000000000   0.000000000000000   1.000000000000000  
slice_coeff = { 1.00000, 0.00000, 0.00000, 0.50000}


CONSTRAINT 1  
FUNCTION:  z = 1
CONTENT 
C1: 0.5*y
C2: -0.5*x
C3: 0

CONSTRAINT 2  
FUNCTION:  y - x

CONSTRAINT 3  
FUNCTION:   -y

CONSTRAINT 4  
FUNCTION:  x - z
CONTENT 
C1: x*y/3
C2:  -(x)^2/3
C3: 0

vertices        /*  coordinates  */    
  1  0.499999598671191                 0                 1  constraints 1 3 
  2  0.349615227370832 0.349615227370831                 1  constraints 1 2 
  3  0.499999971719717 0.499999971719718 0.499999971719718  constraints 2 4 
  4  0.650384457641683                 0 0.650384457641684  constraints 3 4 
  5                  0                 0                 0 fixed  bare 
  6                  0                 0                 1 fixed  bare 
  7                  1                 0                 1 fixed  bare 
  8                  1                 1                 1 fixed  bare 
 14                  0                 0               0.5 fixed  bare 
 15                0.5                 0               0.5 fixed  bare 
 16                0.5               0.5               0.5 fixed  bare 
 17                0.5                 0                 1 fixed  bare 
 18                0.5               0.5                 1 fixed  bare 
 19                  1               0.5                 1 fixed  bare 
 28                  0                 0              0.25 fixed  bare 
 29               0.25                 0              0.25 fixed  bare 
 30               0.25              0.25              0.25 fixed  bare 
 31               0.25                 0                 1 fixed  bare 
 32               0.25              0.25                 1 fixed  bare 
 33                  1              0.25                 1 fixed  bare 
 42                  0                 0              0.75 fixed  bare 
 43               0.75                 0              0.75 fixed  bare 
 44               0.75              0.75              0.75 fixed  bare 
 45               0.75                 0                 1 fixed  bare 
 46               0.75              0.75                 1 fixed  bare 
 47                  1              0.75                 1 fixed  bare 
 63  0.383235856125754 0.383235856125754 0.773520527157395  constraints 2 
 62                  0                 0             0.125 fixed  bare 
 61              0.125                 0             0.125 fixed  bare 
 60              0.125             0.125             0.125 fixed  bare 
 59              0.125                 0                 1 fixed  bare 
 58              0.125             0.125                 1 fixed  bare 
 57                  1             0.125                 1 fixed  bare 
 56  0.461300472193447 0.185826648507894                 1  constraints 1 
 55                  0                 0             0.625 fixed  bare 
 54              0.625                 0             0.625 fixed  bare 
 53              0.625             0.625             0.625 fixed  bare 
 52              0.625                 0                 1 fixed  bare 
 51              0.625             0.625                 1 fixed  bare 
 50                  1             0.625                 1 fixed  bare 
 49                  0                 0             0.375 fixed  bare 
 48              0.375                 0             0.375 fixed  bare 
 41              0.375             0.375             0.375 fixed  bare 
 40              0.375                 0                 1 fixed  bare 
 39              0.375             0.375                 1 fixed  bare 
 38                  1             0.375                 1 fixed  bare 
 37  0.499989940428652 0.198941327855474 0.801049483201394
 36  0.616762037314148 0.226478292015446 0.616762037314148  constraints 4 
 35  0.538694825869336                 0 0.814171314985025  constraints 3 
 34                  0                 0             0.875 fixed  bare 
 27              0.875                 0             0.875 fixed  bare 
 26              0.875             0.875             0.875 fixed  bare 
 25              0.875                 0                 1 fixed  bare 
 24              0.875             0.875                 1 fixed  bare 
 23                  1             0.875                 1 fixed  bare 
 22  0.427931857098653 0.427931857098653 0.650756153257638  constraints 2 
 21                  0                 0            0.0625 fixed  bare 
 20             0.0625                 0            0.0625 fixed  bare 
 13             0.0625            0.0625            0.0625 fixed  bare 
 12             0.0625                 0                 1 fixed  bare 
 11             0.0625            0.0625                 1 fixed  bare 
 10                  1            0.0625                 1 fixed  bare 
  9  0.413761095709996 0.272281917340785                 1  constraints 1 
 64                  0                 0            0.5625 fixed  bare 
 65             0.5625                 0            0.5625 fixed  bare 
 66             0.5625            0.5625            0.5625 fixed  bare 
 67             0.5625                 0                 1 fixed  bare 
 68             0.5625            0.5625                 1 fixed  bare 
 69                  1            0.5625                 1 fixed  bare 
 70                  0                 0            0.3125 fixed  bare 
 71             0.3125                 0            0.3125 fixed  bare 
 72             0.3125            0.3125            0.3125 fixed  bare 
 73             0.3125                 0                 1 fixed  bare 
 74             0.3125            0.3125                 1 fixed  bare 
 75                  1            0.3125                 1 fixed  bare 
 76  0.576967614084525 0.106540294606299 0.721966319583065
 77  0.642178406529872 0.111540908413294 0.642178406529872  constraints 4 
 78   0.50971991454961                 0 0.905886218042882  constraints 3 
 79                  0                 0            0.8125 fixed  bare 
 80             0.8125                 0            0.8125 fixed  bare 
 81             0.8125            0.8125            0.8125 fixed  bare 
 82             0.8125                 0                 1 fixed  bare 
 83             0.8125            0.8125                 1 fixed  bare 
 84                  1            0.8125                 1 fixed  bare 
 85  0.357823956713852 0.357823956713851 0.888459728996982  constraints 2 
 86                  0                 0            0.1875 fixed  bare 
 87             0.1875                 0            0.1875 fixed  bare 
 88             0.1875            0.1875            0.1875 fixed  bare 
 89             0.1875                 0                 1 fixed  bare 
 90             0.1875            0.1875                 1 fixed  bare 
 91                  1            0.1875                 1 fixed  bare 
 92  0.490284682892317 0.0941147381194292                 1  constraints 1 
 93                  0                 0            0.6875 fixed  bare 
 94             0.6875                 0            0.6875 fixed  bare 
 95             0.6875            0.6875            0.6875 fixed  bare 
 96             0.6875                 0                 1 fixed  bare 
 97             0.6875            0.6875                 1 fixed  bare 
 98                  1            0.6875                 1 fixed  bare 
 99                  0                 0            0.4375 fixed  bare 
100             0.4375                 0            0.4375 fixed  bare 
101             0.4375            0.4375            0.4375 fixed  bare 
102             0.4375                 0                 1 fixed  bare 
103             0.4375            0.4375                 1 fixed  bare 
104                  1            0.4375                 1 fixed  bare 
105   0.42302083928974 0.278025687365181  0.89345690379638
106   0.57206942056163 0.349244884558315  0.57206942056163  constraints 4 
107  0.586241727830633                 0 0.727720018361797  constraints 3 
108                  0                 0            0.9375 fixed  bare 
109             0.9375                 0            0.9375 fixed  bare 
110             0.9375            0.9375            0.9375 fixed  bare 
111             0.9375                 0                 1 fixed  bare 
112             0.9375            0.9375                 1 fixed  bare 
113                  1            0.9375                 1 fixed  bare 
114  0.529097081502525 0.100326160962798  0.81059034169527
115  0.470922488676783 0.189418221698278  0.89967817282689
116  0.499991078999371 0.0958574956708887 0.904138723697271
117  0.499996701620053 0.319213790116357 0.680781191831386
118  0.451491185492441  0.29427564115608 0.787061202259824
119  0.548520986383996 0.212944838110806 0.705733054164729

edges  
  2       3   22      constraints 2 
  5       5   21    fixed  bare 
  6       5   20    fixed  bare 
  7       5   13    fixed  bare 
  8       6   12    fixed  bare 
  9       6   11    fixed  bare 
 10       7   10    fixed  bare 
 15       2    9      constraints 1  original 1
 19      14   64    fixed  bare  original 5
 20      15   65    fixed  bare  original 6
 21      16   66    fixed  bare  original 7
 22      17   67    fixed  bare  original 8
 23      18   68    fixed  bare  original 9
 24      19   69    fixed  bare  original 10
 45      28   70    fixed  bare  original 5
 46      29   71    fixed  bare  original 6
 47      30   72    fixed  bare  original 7
 48      31   73    fixed  bare  original 8
 49      32   74    fixed  bare  original 9
 50      33   75    fixed  bare  original 10
 53       4   76    
 57       4   77      constraints 4  original 3
 58       1   78      constraints 3  original 4
 59      42   79    fixed  bare  original 5
 60      43   80    fixed  bare  original 6
 61      44   81    fixed  bare  original 7
 62      45   82    fixed  bare  original 8
 63      46   83    fixed  bare  original 9
 64      47   84    fixed  bare  original 10
128      63   85      constraints 2  original 2
127      62   86    fixed  bare  original 5
126      61   87    fixed  bare  original 6
125      60   88    fixed  bare  original 7
124      59   89    fixed  bare  original 8
123      58   90    fixed  bare  original 9
122      57   91    fixed  bare  original 10
121      56   92      constraints 1  original 1
120      55   93    fixed  bare  original 5
119      54   94    fixed  bare  original 6
118      53   95    fixed  bare  original 7
117      52   96    fixed  bare  original 8
116      51   97    fixed  bare  original 9
115      50   98    fixed  bare  original 10
114      49   99    fixed  bare  original 5
113      48  100    fixed  bare  original 6
112      41  101    fixed  bare  original 7
111      40  102    fixed  bare  original 8
110      39  103    fixed  bare  original 9
109      38  104    fixed  bare  original 10
108      37  105    
107      36  106      constraints 4  original 3
106      35  107      constraints 3  original 4
105      34  108    fixed  bare  original 5
104      27  109    fixed  bare  original 6
103      26  110    fixed  bare  original 7
102      25  111    fixed  bare  original 8
101      24  112    fixed  bare  original 9
100      23  113    fixed  bare  original 10
 99      37  114    
 98      56  115    
 97      35  116    
 96      63  117    
 95      37  118    
 94      36  119    
 93      22   63      constraints 2  original 2
 92      21   62    fixed  bare  original 5
 91      20   61    fixed  bare  original 6
 90      13   60    fixed  bare  original 7
 89      12   59    fixed  bare  original 8
 88      11   58    fixed  bare  original 9
 87      10   57    fixed  bare  original 10
 86       9   56      constraints 1  original 1
 85      64   55    fixed  bare  original 5
 84      65   54    fixed  bare  original 6
 83      66   53    fixed  bare  original 7
 82      67   52    fixed  bare  original 8
 81      68   51    fixed  bare  original 9
 80      69   50    fixed  bare  original 10
 79      70   49    fixed  bare  original 5
 78      71   48    fixed  bare  original 6
 77      72   41    fixed  bare  original 7
 76      73   40    fixed  bare  original 8
 75      74   39    fixed  bare  original 9
 74      75   38    fixed  bare  original 10
 73      76   37    
 72      77   36      constraints 4  original 3
 71      78   35      constraints 3  original 4
 70      79   34    fixed  bare  original 5
 69      80   27    fixed  bare  original 6
 68      81   26    fixed  bare  original 7
 67      82   25    fixed  bare  original 8
 66      83   24    fixed  bare  original 9
 65      84   23    fixed  bare  original 10
 56      85    2      constraints 2  original 2
 55      86   28    fixed  bare  original 5
 54      87   29    fixed  bare  original 6
 52      88   30    fixed  bare  original 7
 51      89   31    fixed  bare  original 8
 44      90   32    fixed  bare  original 9
 43      91   33    fixed  bare  original 10
 42      92    1      constraints 1  original 1
 41      93   42    fixed  bare  original 5
 40      94   43    fixed  bare  original 6
 39      95   44    fixed  bare  original 7
 38      96   45    fixed  bare  original 8
 37      97   46    fixed  bare  original 9
 36      98   47    fixed  bare  original 10
 35      99   14    fixed  bare  original 5
 34     100   15    fixed  bare  original 6
 33     101   16    fixed  bare  original 7
 32     102   17    fixed  bare  original 8
 31     103   18    fixed  bare  original 9
 30     104   19    fixed  bare  original 10
 29     105    2    
 28     106    3      constraints 4  original 3
 27     107    4      constraints 3  original 4
 26     108    6    fixed  bare  original 5
 25     109    7    fixed  bare  original 6
 18     110    8    fixed  bare  original 7
 17     111    7    fixed  bare  original 8
 16     112    8    fixed  bare  original 9
 14     113    8    fixed  bare  original 10
 13     114   35    
 12     115   37    
 11     116   56    
  4     117   36    
  3     118   63    
  1     119   37    
129     116  115    
130     114  116    
131     115  114    
132     119  118    
133     117  119    
134     118  117    
135      76  107    
136     114   76    
137     107  114    
138     105  115    
139       9  105    
140     115    9    
141     116   78    
142      92  116    
143      78   92    
144      22  106    
145     117   22    
146     106  117    
147      85  118    
148     105   85    
149     118  105    
150     119   77    
151      76  119    
152      77   76    

faces    /* edge loop */      
 21   -131 -129 -130 /*area 0.00480923*/ original 1
 56   -134 -132 -133 /*area 0.00698116*/ original 1
 64   -137 -135 -136 /*area 0.00539177*/ original 1
 63   -140 -138 -139 /*area 0.00539185*/ original 1
 62   -143 -141 -142 /*area 0.0046417*/ original 1
 61   -146 -144 -145 /*area 0.00893235*/ original 1
 60   -149 -147 -148 /*area 0.00574283*/ original 1
 59   -152 -150 -151 /*area 0.00574288*/ original 1
 58   -11 129 -98 /*area 0.00493877*/ original 1
 57   -97 -13 130 /*area 0.00493883*/ original 1
 55   131 -99 -12 /*area 0.00530648*/ original 1
 54   -1 132 -95 /*area 0.00581613*/ original 1
 53   -94 -4 133 /*area 0.00674369*/ original 1
 52   134 -96 -3 /*area 0.00674371*/ original 1
 51   53 135 27 /*area 0.00537977*/ original 1
 50   73 99 136 /*area 0.00521043*/ original 1
 49   137 13 106 /*area 0.00497447*/ original 1
 48   108 138 12 /*area 0.00521047*/ original 1
 47   29 15 139 /*area 0.00537983*/ original 1
 46   140 86 98 /*area 0.00497438*/ original 1
 45   97 141 71 /*area 0.00463398*/ original 1
 44   11 121 142 /*area 0.00463404*/ original 1
 43   143 42 58 /*area 0.00447571*/ original 1
 42   2 144 28 /*area 0.0143456*/ original 1
 41   93 96 145 /*area 0.008849*/ original 1
 40   146 4 107 /*area 0.00884901*/ original 1
 39   128 147 3 /*area 0.00672046*/ original 1
 38   56 -29 148 /*area 0.00577478*/ original 1
 37   149 -108 95 /*area 0.00594737*/ original 1
 36   94 150 72 /*area 0.00672042*/ original 1
 35   1 -73 151 /*area 0.0059474*/ original 1
 34   152 -53 57 /*area 0.00577484*/ original 1

bodies  /* facets */
  1       21 56 64 63 62 61 60 59 58 57 \
           55 54 53 52 51 50 49 48 47 46 \
           45 44 43 42 41 40 39 38 37 36 \
           35 34  volume 0.0833333333333333  /*actual: 0.0833333333333333*/ lagrange_multiplier 6.66232834446316e-005  centerofmass 

read

metric_conversion off
autorecalc on
gv_binary off
gravity off
transform_expr "dcbdcbdcb"


//Procedures and functions forward declarations:
showcube := {}
showtwo := {}
showfour := {}
showeight := {}
show64 := {}
setcolor := {}
gogo := {}
gogo2 := {}
// Procedures without arguments:
showcube := { transform_expr "dcbdcbdcb"; 
  transforms ON; 
  if ( not band_flag ) then 
    show_expr edges where valence == 1; 
  show_trans "Rrrdd"
}
showtwo := { transform_expr "fdcbdcbdcb"; 
  transforms ON; 
  if ( not band_flag ) then 
    show_expr edges where valence == 1; 
  show_trans "Rrrdd"
}
showfour := { transform_expr "fadcbdcbdcb"; 
  transforms ON; 
  if ( not band_flag ) then 
    show_expr edges where valence == 1; 
  show_trans "Rrrdd"
}
showeight := { transform_expr "aefdcbdcbdcb"; 
  transforms ON; 
  if ( not band_flag ) then 
    show_expr edges where valence == 1; 
  show_trans "Rrrdd"
}
show64 := { transform_expr "ghiaefdcbdcbdcb"; 
  transforms ON; 
  if ( not band_flag ) then 
    show_expr edges where valence == 1; 
  show_trans "Rrrdd"
}
setcolor := { set facets backcolor (14)
}
gogo := { g 5; 
  r; 
  g 5; 
  r; 
  g 5; 
  r; 
  g 10; 
  u; 
  refine edges where on_constraint 2; 
  refine edges where on_constraint 4; 
  hessian; 
  hessian 
}
gogo2 := { g 5; 
  r; 
  g 5; 
  r; 
  g 10; 
  u; 
  refine edges where on_constraint 2; 
  refine edges where on_constraint 4; 
  hessian; 
  hessian 
}
show_expr edges where valence == 1
